# Config
LOG_FILE = 'logFile'
CHROMIUM = 'chromium'
ENTORNO_DOCKER = 'entornoDocker'
BUCLE_INFINITO = 'bucleInfinito'
BUSCAR_CARTAS_NUEVAS = 'buscarCartasNuevas'
CANTIDAD_BUSQUEDAS = 'cantidadBusquedas'
COLECCIONES_BUSQUEDAS = 'coleccionesBusquedas'
COPIAR_FORMULA = 'copiarFormula'
COPIAR_DATOS_GENERALES = 'copiarDatosGenerales'
COPIAR_IMAGEN = 'copiarImagen'
COPIAR_IMAGEN_CM_FORZADO = 'copiarImagenCmForzado'
COPIAR_IMAGEN_CM = 'copiarImagenCm'
COPIAR_CODIGO_IMAGEN = 'copiarCodigoImagen'
DIFERENCIA_IMG = 'diferenciasImg'
DESCARGAR_IMAGENES = 'descargarImagenes'
ENVIAR_SIN_PRECIO = 'enviarSinPrecio'
FORZAR_PRIMERA_BUSQUEDA = 'forzarPrimeraBusqueda'
MODO_BUSCADOR = 'modoBuscador'
FINDER_TELE = 'buscadorNotificaTelegram'
MODO_ESCANEO = 'modoEscaneo'
TELEGRAM_BOT_TOKEN = 'telegramBotToken'
TELEGRAM_CHAT_CANAL_CHOLLOS_ID = 'telegramChatCanalChollosId'
TELEGRAM_CHAT_CANAL_CARTAS_ID = 'telegramChatCanalCartasId'
TELEGRAM_LOG_CHAT_ID = 'telegramLogChatId'
TIEMPO_MINIMO_BUSQUEDA = 'tiempoMinimoBusqueda'
TIEMPO_MINIMO_BUSQUEDA_SPREADSHEET = 'tiempoMinimoBusquedaSpreadsheet'
TIEMPO_MINIMO_BUSQUEDA_TELEGRAM = 'tiempoMinimoBusquedaTelegram'
WORKBOOK_NAME = 'workbookName'

# Urls templates
URL_TEMPLATE_GLOBAL = 'https://world.digimoncard.com/images/cardlist/card/'
URL_TEMPLATE_GLOBAL_20220811 = 'https://s3.amazonaws.com/prod.bandaitcgplus.files.api/card_image/DG-EN/'
URL_TEMPLATE_JP = 'https://digimoncard.com/images/cardlist/card/'
URLS_IMG_FORMAT = '.png'
URL_API_DATOS = 'https://digimoncard.io/api-public/search.php?card={}'

# Mapas finder
CANTIDAD = 'can'
FORMAT = 'form'
PREFIJO = 'pre'
TEMPORADA = 'temp'

PRE_TEMP_BT = 'BT'
PRE_TEMP_EX = 'EX'
PRE_TEMP_P = 'P'
PRE_TEMP_ST = 'ST'
PRE_ALTER = '_P'
PRE_ALTER_20220811 = 'P'
SEPARADOR_TEMP = '-'
SEPARADOR_CONFIG = ','
TAG_SELLADO = '-SLL'

WEB_TRADER = 'CardTrader'
WEB_MARKET = 'CardMarket'

TAMANHO_MIN_IMG = 3000

# Sheet
SHEET_NAME_ALBUM = 'Album'
SHEET_NAME_DATOS = 'Datos'
SHEET_NAME_PRECIOS_AUX = 'Precios Aux'
SHEET_NAME_PRECIOS_MARKET = 'Precios Market'
SHEET_NAME_PRECIOS_TRADER = 'Precios Trader'
SHEET_NAME_IMGS = 'IMGs'

FILA = 'fila'

# Campos Sheet
ACTUAL = 'Actual'
ALARMA = 'Alarma'
BUSCAR = 'Buscar'
CODIGO = 'Código'
CODIGOJP = 'CódigoJP'
CODIGOEU = 'CódigoEU'
COLOR = 'Color'
COMPRA = 'Compra'
DP = 'DP'
EVOL = 'Evol'
FMINIMO = 'FMinimo'
MAIN_EFF = 'Main Effect'
MINIMO = 'Minimo'
NOMBRE = 'Nombre'
NUMERO = 'Número'
PLAY = 'Play'
SOUR_EFF = 'Source Effect'
TIPO = 'Tipo'
URL_IMAGEN = 'URL Imagen'
URL_JAPO = 'URL Japo'
URL_PRECIO = 'URL Precio'
NOTIFICAR_EU = 'Notificar EU'
NOTIFICAR_JP = 'Notificar JP'
EU_JP = 'EU-JP'
EU_CM = 'EU-CM'
IMAGEN_EU = 'imgEu'
IMAGEN_OTRO = 'imgOtro'
FORMATEO_IMG = 'img_{}.png'
FORMATEO_1 = '{}'
FORMATEO_2 = '{}_dummy'
FORMATEO_3 = 'e_{}_dummy'
FORMATEO_4 = 'e_{}_D'
FORMATEO_4_P1 = 'e_{}p_D'
FORMATEO_5 = 'e_{}_D_sam'
FORMATEO_5_P1 = 'e_{}P_D_sam'

FRM_DA_D = '=IF(IFERROR(SEARCH(\"MN-\";A{})>0;FALSE);\"MANUAL\";ARRAY_CONSTRAIN(SPLIT(A{};\"-\";FALSE);1;1))'
FRM_DA_E = '=IFERROR(REPLACE(A{};SEARCH(\"_\";A{});99;\"\");A{})'
FRM_DA_P = '=IMAGE(N{})'
FRM_DA_Q = '=IMAGE(O{})'
